name = "fullstack-blog"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"
# D1 Database binding
[[d1_databases]]
binding = "fullstack_blog_db"
database_name = "fullstack-blog-db"
database_id = "08a8543d-4538-4620-8912-1b2af65e2ace"

# R2 Bucket binding
[[r2_buckets]]
binding = "MEDIA"
bucket_name = "fullstack-blog-media"

# KV Cache binding
[[kv_namespaces]]
binding = "CACHE"
id = "4020f0e4252e466490305acf6317f6e5"

# Workers AI binding
[ai]
binding = "AI"
